inherit_from:
  - 'https://raw.githubusercontent.com/feracommerce/code-standards/master/.rubocop.yml'
  - 'https://raw.githubusercontent.com/feracommerce/code-standards/master/.rubocop-rspec.yml'
inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 2.3
require:
  - rubocop-rspec
