# Base was copied from https://github.com/sider/meowcop/blob/master/config/rubocop.yml which is what Sider uses by default
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - '*/spec/**/*'
    - 'lib/tasks/one_offs/**/*' # We don't really care about linting one-off tasks
    - 'app/migrators/**/*' # Migrators are one-off tasks so there isn't much need to lint them
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false # We actually believe that it is more readable with premature returns
Style/MapToHash:
  Enabled: false # We believe it's more readable to use map vs hash with block syntax
Layout/BeginEndAlignment:
  Enabled: false # We believe it's more readable to have begin blocks aligned to the end blocks (and also helps with code smells)
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
# The cop reports not reasonable issues. So, disabled.
# See. http://tech.sideci.com/entry/2016/11/01/105900
Lint/EmptyWhen:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 60
  Enabled: false
Metrics/BlockLength:
  Max: 200
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    # In many cases, config/routes.rb has very long block
    - 'config/routes.rb'
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 60
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: true
  Max: 4
# Use the default setting
Metrics/PerceivedComplexity:
  Enabled: false
Security/Eval:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/EmptyLinesAroundBeginBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/HeredocArgumentClosingParenthesis:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/FirstParameterIndentation:
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/InitialIndentation:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/LineLength:
  Max: 200
  AllowedPatterns: ['^\s*#', '^\s*([a-zA-Z]*[lL]og[a-zA-Z]*)[ (]', '^\s*[''"]', '.*#.{30,300}', '^\s*[a-z_]:\s*".+",?[}\s]*$']
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Layout/MultilineHashBraceLayout:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/SpaceAfterColon:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAfterMethodName:
  Enabled: false
Layout/SpaceAfterNot:
  Enabled: false
Layout/SpaceAfterSemicolon:
  Enabled: false
Layout/SpaceAroundBlockParameters:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/SpaceAroundKeyword:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceBeforeComma:
  Enabled: false
Layout/SpaceBeforeComment:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceBeforeSemicolon:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideRangeLiteral:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/DefEndAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/ClosingHeredocIndentation:
  Enabled: false
Layout/LeadingEmptyLines:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/ConstantName:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/VariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/BlockParameterName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

# THIS BLOCK IS AUTO-GENERATED. DO NOT EDIT.
# === Disabled cops: BEGIN ===
Style/AccessModifierDeclarations:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/Alias:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/ArrayCoercion:
  Enabled: false
Style/ArrayJoin:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Attr:
  Enabled: false
Style/AutoResourceCleanup:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BeginBlock:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/ClassMethods:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/ColonMethodDefinition:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/ConstantVisibility:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/Dir:
  Enabled: false
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/DoubleCopDisableDirective:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyBlockParameter:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLambdaParameter:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/EndBlock:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/FloatDivision:
  Enabled: false
Style/For:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IfUnlessModifierOfIfUnless:
  Enabled: false
Style/IfWithSemicolon:
  Enabled: false
Style/ImplicitRuntimeError:
  Enabled: false
Style/InfiniteLoop:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/IpAddresses:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/MinMax:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineIfThen:
  Enabled: false
Style/MultilineMemoization:
  Enabled: false
Style/MultilineMethodSignature:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MultilineWhenThen:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedUnless:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/NestedModifier:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/OptionHash:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/OrAssignment:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RandomWithOffset:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantCapitalW:
  Enabled: false
Style/RedundantCondition:
  Enabled: false
Style/RedundantConditional:
  Enabled: false
Style/RedundantException:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/RedundantFreeze:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RedundantSort:
  Enabled: false
Style/RedundantSortBy:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/ReturnNil:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/Sample:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/Send:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StringMethods:
  Enabled: false
Style/Strip:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TrailingBodyOnClass:
  Enabled: false
Style/TrailingBodyOnMethodDefinition:
  Enabled: false
Style/TrailingBodyOnModule:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInBlockArgs:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingMethodEndStatement:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
Style/VariableInterpolation:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
